"""empty message

Revision ID: 1456fc4a237
Revises: None
Create Date: 2015-03-04 17:48:25.738305

"""

# revision identifiers, used by Alembic.
revision = '1456fc4a237'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
